# Site settings
# Change these ↓↓↓
title: "Bisman Singh"
description: "Research notes, mini-blogs, and experiments in graphs, ML, and quant."
author: Bisman Singh
url: "https://<your-username>.github.io"

# Build settings
markdown: kramdown
theme: minima
permalink: /:categories/:year/:month/:day/:title/

# Minima theme options
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/<your-username>" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/siddharth101/" }

# Enable MathJax for LaTeX (optional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Tags & categories (no extra config needed, just use front matter)
