# Site settings
title: "Bisman Singh"
description: "Research notes, mini-blogs, and experiments in graphs, ML, and quant."
author: Bisman Singh
url: "https://bis1999.github.io"   # <-- set to your actual URL (or delete this line)

# Build settings
markdown: kramdown
theme: minima
permalink: /:categories/:year/:month/:day/:title/

# Minima theme options
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/bis1999" }  # <-- update
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/siddharth101/" }

# Enable MathJax for LaTeX (optional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
